(ns dk.cst.corpus-probe.cwb.parse
  "Parsers turning CQP terminal output into plain data, each written
  against a byte-exact golden file captured from a real CQP session
  (test/resources/golden/, regenerated by dev/capture-golden.sh). KWIC
  lines are expected in the hardened display profile of
  dk.cst.corpus-probe.search.batch/hardened-profile, where every separator
  is a TAB-framed marker letter (see `markers`)."
  (:require [clojure.string :as str]))

(def markers
  "The marker letters of the hardened display profile, each framed by TABs
  in the output, by what it separates: attribute values inside a token,
  tokens, the left context from the match, the match from the right
  context, and a structure tag from the tokens around it."
  {:attribute "A"
   :token     "T"
   :left      "L"
   :right     "R"
   :structure "S"})

(defn- finish-token
  "Close the token accumulating in `acc` and file it under the current zone."
  [{:keys [attrs zone parts open close] :as acc}]
  (-> acc
      (cond-> (or (seq (remove empty? parts)) (seq open) (seq close))
        (update zone conj (cond-> (zipmap attrs parts)
                            (seq open)  (assoc :open open)
                            (seq close) (assoc :close close))))
      (assoc :parts [] :open [] :close [])))

(defn- add-tag
  "Record structure tag `v` (e.g. \"<s>\" or \"</s>\") on the token in `acc`."
  [acc v]
  (let [close? (str/starts-with? v "</")
        tag    (keyword (str/replace v #"[</>]" ""))]
    (update acc (if close? :close :open) conj tag)))

(defn kwic-line->hit
  "Parse one hardened-profile KWIC `line` into a hit map with the token
  attributes named by `attrs` (in the order they are shown): {:cpos <n>
  :left [token ...] :match [...] :right [...]}, each token a map of
  attribute to value, plus :open/:close vectors of structure-tag keywords
  when tags are shown. Throws when `line` lacks the corpus-position prefix
  of a KWIC line."
  [attrs line]
  (let [[_ cpos content] (re-matches #"(?s)\s*(\d+): (.*)" line)
        _      (when-not cpos
                 (throw (ex-info "Not a KWIC line" {:line line})))
        {:keys [attribute token left right structure]} markers
        ;; TAB never occurs inside a value, so the fields alternate
        ;; strictly between values and markers
        fields (str/split content #"\t" -1)
        pairs  (partition-all 2 fields)
        triples (map (fn [[v m] prev-m] [v m prev-m])
                     pairs
                     (cons nil (map second pairs)))]
    (-> (reduce
         (fn [{:keys [in-tag?] :as acc} [v m prev-m]]
           (let [acc (cond
                       in-tag?
                       (add-tag acc v)

                       ;; an empty field beside a frame marker is glue; one
                       ;; beside an A marker is an empty attribute value
                       (or (not-empty v) (= prev-m attribute) (= m attribute))
                       (update acc :parts conj v)

                       :else acc)]
             (condp = m
               attribute acc
               structure (update acc :in-tag? not)
               token     (finish-token acc)
               left      (-> acc finish-token (assoc :zone :match))
               right     (-> acc finish-token (assoc :zone :right))
               nil       (finish-token acc))))
         {:attrs attrs :zone :left :in-tag? false
          :parts [] :open [] :close []
          :left [] :match [] :right []}
         triples)
        (select-keys [:left :match :right])
        (assoc :cpos (parse-long cpos)))))

(defn kwic->hits
  "Parse hardened-profile KWIC `lines` (from `cat`) using `attrs`."
  [attrs lines]
  (mapv (partial kwic-line->hit attrs) lines))

(defn- bounds
  "The sides of `hit` on which its context has reached the edge of the
  region of `attr`: `:start`, `:end`, both or neither. A side it has not
  reached is one a wider context would give more of."
  [attr {:keys [left match right]}]
  (cond-> #{}
    (some #{attr} (:open (first (concat left match))))  (conj :start)
    (some #{attr} (:close (last (concat match right)))) (conj :end)))

(defn clip-context
  "`hit` with its context cut back to the region of s-attribute `attr`
  its match is in, by the tags the tokens carry: CQP counts a context in
  words, so a wide one runs on into the neighbouring regions, whose
  words are not this hit's text. What it now reaches is its `:bounds`
  (see `bounds`), which say where there is no more to fetch. Left alone
  for a nil `attr`, and for a hit whose tokens carry no tags."
  [attr {:keys [left right] :as hit}]
  (if-not attr
    hit
    ;; the boundary token belongs to the region it bounds, so it is kept
    (let [upto    (fn [tag tokens]
                    (let [[in out] (split-with #(not (some #{attr} (tag %)))
                                               tokens)]
                      (concat in (take 1 out))))
          clipped (assoc hit
                         :left  (vec (reverse (upto :open (rseq left))))
                         :right (vec (upto :close right)))
          reached (bounds attr clipped)]
      (cond-> clipped
        (seq reached) (assoc :bounds reached)))))

(defn show-cd->attributes
  "Parse `lines` from `show cd;` into attribute descriptions.

  Returns [{:type :positional/:structural/:alignment :name <kw>
  :values? <bool> :shown? <bool>} ...] in registry order."
  [lines]
  (vec (for [line lines
             :let [[type name values shown] (str/split line #"\t" -1)]
             :when (not-empty type)]
         {:type    ({"p-Att" :positional
                     "s-Att" :structural
                     "a-Att" :alignment} type)
          :name    (keyword name)
          :values? (= values "-V")
          :shown?  (= shown "*")})))

(defn dump->anchors
  "Parse `lines` from `dump` into anchor maps, one per match: [{:match <n>
  :matchend <n> :target <n or nil> :keyword <n or nil>} ...]; CQP prints
  -1 for an unset anchor, translated to nil."
  [lines]
  (mapv (fn [line]
          (let [[match matchend target keyword*]
                (map parse-long (str/split line #"\t"))]
            {:match    match
             :matchend matchend
             :target   (when-not (= -1 target) target)
             :keyword  (when-not (= -1 keyword*) keyword*)}))
        lines))

(defn size->n
  "Parse `lines` from `size` (one line, the number of matches) into that
  number."
  [lines]
  (parse-long (first lines)))

(defn tabulate->rows
  "Realign the `sections` printed by one `tabulate` command each, one line
  per hit, into one row per hit: a vector of the sections' lines at that
  hit, in section order; empty for no sections."
  [sections]
  (if (seq sections)
    (apply mapv vector sections)
    []))

(defn group->freqs
  "Parse `lines` from `group` into frequency maps [{:values [<s>] :freq
  <n>} ...]."
  [lines]
  (mapv (fn [line]
          ;; split from the right: a value may hold a TAB
          (let [[_ value freq] (re-matches #"(?s)(.*)\t(\d+)" line)]
            {:values [value] :freq (parse-long freq)}))
        lines))

(defn group-pairs->freqs
  "Parse `lines` from `group ... by ...` into frequency maps [{:values
  [<counted> <counted against>] :freq <n>} ...], the values in the order
  the command names them; CQP prints them the other way round."
  [lines]
  (mapv (fn [line]
          ;; split from the right: a TAB in the value counted against
          ;; survives, one in the counted value does not
          (let [[_ by value freq] (re-matches #"(?s)(.*)\t([^\t]*)\t(\d+)"
                                              line)]
            {:values [value by] :freq (parse-long freq)}))
        lines))

(defn count->freqs
  "Parse `lines` from `count` (with PrettyPrint off: frequency TAB first
  line TAB string) into frequency maps [{:values [<s>] :freq <n>} ...],
  in the order printed, which is by descending frequency."
  [lines]
  (mapv (fn [line]
          ;; no token holds a TAB, so the two before the string are the
          ;; only ones on the line
          (let [[freq _ string] (str/split line #"\t" 3)]
            {:values [string] :freq (parse-long freq)}))
        lines))

(defn info->map
  "Parse `lines` from `info;` into corpus facts {:name <s> :size <n>
  :charset <s> :properties {<kw> <s>} :info <s>}, :info being the free
  text of the corpus's .info file."
  [lines]
  ;; only the header block is parsed, or a colon-shaped line of the .info
  ;; text would clobber a fact
  (let [[header body] (split-with (complement str/blank?) lines)
        info          (str/join "\n" (drop-while str/blank? body))]
    (cond-> (reduce (fn [m line]
                      (if-let [[_ k v] (re-matches #"([A-Za-z]+):\s*(.*)" line)]
                        (case k
                          "Name"    (assoc m :name v)
                          "Size"    (assoc m :size (parse-long v))
                          "Charset" (assoc m :charset v)
                          m)
                        (if-let [[_ k v] (re-matches #"\t(\S+) = '(.*)'" line)]
                          (assoc-in m [:properties (keyword k)] v)
                          m)))
                    {:properties {}}
                    header)
      (not-empty info) (assoc :info info))))
