(ns dk.cst.corpus-probe.cwb.tools
  "Read-only wrappers for the cwb-* command-line tools, and the parsers of
  what they print: `cwb-describe-corpus` gives the corpus info pages their
  statistics, `cwb-lexdecode` whole-corpus frequency lists, `cwb-s-decode`
  the metadata filters their value lists and the breakdowns the size of
  the text behind each value. Each parser is written against a golden
  file (test/resources/golden/, regenerated by dev/capture-golden.sh)."
  (:require [clojure.string :as str]
            [dk.cst.corpus-probe.cwb :as cwb]
            [dk.cst.corpus-probe.cwb.command :as command]
            [dk.cst.corpus-probe.cwb.corpus :as corpus]))

(def tool-names
  "The CWB programs run here besides cqp. Each is invoked by bare name, so
  the PATH that reaches cqp has to reach these too."
  ["cwb-describe-corpus" "cwb-lexdecode" "cwb-s-decode"])

(defn run-tool!
  "Run the cwb tool command vector `cmd` for `corpus` via `ctx` (as
  dk.cst.corpus-probe.cwb.corpus/corpus-ctx configures it) and return its
  stdout lines, decoded in the corpus charset. Throws on `ctx`'s
  :timeout-ms (default 30000) and on a non-zero exit, with the tool's
  error text."
  [{:keys [timeout-ms charset] :or {timeout-ms 30000 charset "UTF-8"} :as ctx}
   corpus cmd]
  (let [res (cwb/run! cmd timeout-ms {:charset charset})]
    (when (cwb/timeout? res)
      (throw (ex-info "cwb tool timed out"
                      {:corpus corpus :cmd cmd :timeout-ms timeout-ms})))
    (when-not (zero? (:exit res))
      (throw (ex-info "cwb tool failed"
                      {:corpus corpus :cmd cmd :exit (:exit res)
                       :message (:error (cwb/stderr->outcome (:err res)))})))
    (str/split (:out res) #"\n")))

(defn describe->stats
  "Parse `lines` from `cwb-describe-corpus -s` (one corpus) into {:name <s>
  :description <s> :charset <s> :size <n> :p-attrs [{:name <kw> :tokens <n>
  :types <n>} ...] :s-attrs [{:name <kw> :regions <n> :values? <bool>} ...]
  :a-attrs [{:name <kw> :blocks <n>} ...]}, attributes in registry order;
  an attribute the tool prints NO DATA for keeps its name with nil counts,
  and a corpus with no readable data has no :size."
  [lines]
  (reduce (fn [m line]
            (condp re-matches line
              #"Corpus:\s+(\S+)" :>> (fn [[_ v]] (assoc m :name v))
              #"description:\s+(\S.*?)\s*" :>> (fn [[_ v]]
                                                 (assoc m :description v))
              #"encoding:\s+(\S+)\s*" :>> (fn [[_ v]] (assoc m :charset v))
              #"size \(tokens\):\s+(\d+)\s*" :>>
              (fn [[_ v]] (assoc m :size (parse-long v)))

              #"p-ATT (\S+)\s+(\d+) tokens,\s+(\d+) types\s*" :>>
              (fn [[_ n tokens types]]
                (update m :p-attrs conj {:name   (keyword n)
                                         :tokens (parse-long tokens)
                                         :types  (parse-long types)}))
              #"s-ATT (\S+)\s+(\d+) regions( \(with annotations\))?\s*" :>>
              (fn [[_ n regions values]]
                (update m :s-attrs conj {:name    (keyword n)
                                         :regions (parse-long regions)
                                         :values? (some? values)}))
              #"a-ATT (\S+)\s+(\d+) .*" :>>
              (fn [[_ n blocks]]
                (update m :a-attrs conj {:name   (keyword n)
                                         :blocks (parse-long blocks)}))
              #"([psa])-ATT (\S+)\s+NO DATA\s*" :>>
              (fn [[_ type n]]
                (update m ({"p" :p-attrs "s" :s-attrs "a" :a-attrs} type)
                        conj {:name (keyword n)}))
              m))
          {:p-attrs [] :s-attrs [] :a-attrs []}
          lines))

(defn describe-corpus!
  "Describe `corpus` (an uppercase CQP corpus name) with per-attribute
  statistics via `cwb-describe-corpus -s` against the `ctx` registry,
  cached until the corpus is re-encoded: the map of `describe->stats`.
  Throws when the tool fails or times out, or reports no size."
  [ctx corpus]
  (command/valid-corpus-name corpus)
  (corpus/facts!
   ctx corpus ::describe
   (fn []
     (let [ctx   (corpus/corpus-ctx ctx corpus)
           stats (describe->stats
                  (run-tool! ctx corpus ["cwb-describe-corpus"
                                         "-r" (:registry ctx)
                                         "-s" (str corpus)]))]
       ;; the tool exits 0 for an entry whose data files are gone,
       ;; printing ERROR in place of the size
       (when (nil? (:size stats))
         (throw (ex-info "cwb-describe-corpus reported missing corpus data"
                         {:corpus corpus :phantom? true})))
       stats))))

(defn lexdecode->freqs
  "Parse `lines` from `cwb-lexdecode -fb` (frequency TAB value, one line
  per lexicon entry) into frequency maps [{:values [<s>] :freq <n>} ...]
  sorted by descending frequency, the shape of
  dk.cst.corpus-probe.cwb.parse/group->freqs."
  [lines]
  (->> (remove str/blank? lines)
       (map (fn [line]
              (let [[freq value] (str/split line #"\t" 2)]
                {:values [value] :freq (parse-long freq)})))
       (sort-by :freq >)
       (vec)))

(defn lexicon!
  "The frequency lexicon of positional attribute `attr` of `corpus` (an
  uppercase CQP corpus name) via `cwb-lexdecode -f` against the `ctx`
  registry: [{:values [<s>] :freq <n>} ...] sorted by frequency (see
  `lexdecode->freqs`). `attr` must be a positional attribute of the
  corpus."
  ;; TODO: stream large lexicons and exports row by row instead of
  ;; building them in memory (milestone 5, with the NQR caching).
  [ctx corpus attr]
  ;; not cached: a large lexicon runs to millions of entries, too much
  ;; heap to keep for the JVM's lifetime
  (let [ctx (corpus/corpus-ctx ctx corpus)]
    (when-not (corpus/positional?
               (corpus/attribute (corpus/attributes! ctx corpus) attr))
      (throw (ex-info "Not a positional attribute of this corpus"
                      {:corpus corpus :attr attr})))
    (lexdecode->freqs
     (run-tool! ctx corpus ["cwb-lexdecode" "-r" (:registry ctx)
                            "-fb" "-P" (name attr) (str corpus)]))))

(def value-limit
  "The most distinct values an annotated s-attribute may have and still be
  offered as a metadata filter: a longer list of checkboxes is no usable
  control."
  500)

(def region-limit
  "The most regions an s-attribute may have before its values are not even
  decoded: one with millions of regions (sentence IDs, say) all but always
  exceeds `value-limit`, and decoding it costs seconds."
  1000000)

(defn attribute-values!
  "The values of positional attribute `attr` of `corpus` (an uppercase
  CQP corpus name) via `ctx`, in lexicon order, cached until the corpus
  is re-encoded; nil when the corpus lacks the attribute or it has more
  than `value-limit` types, which are no list a reader could pick from."
  [ctx corpus attr]
  (command/valid-corpus-name corpus)
  (corpus/facts!
   ctx corpus [::attribute-values (keyword attr)]
   (fn []
     (let [types (:types (corpus/attribute
                          (:p-attrs (describe-corpus! ctx corpus)) attr))]
       (when (and types (<= types value-limit))
         (mapv (comp first :values) (lexicon! ctx corpus attr)))))))

(defn annotation-stats!
  "The describe statistics of annotated s-attribute `attr` of `corpus`
  (an uppercase CQP corpus name) via `ctx`: its name and its region
  count (see `describe-corpus!`). Throws for anything but an annotated
  s-attribute of the corpus, since the names are spliced into a command."
  [ctx corpus attr]
  (let [stats (corpus/attribute (:s-attrs (describe-corpus! ctx corpus))
                                attr)]
    (when-not (:values? stats)
      (throw (ex-info "Not an annotated structural attribute of this corpus"
                      {:corpus corpus :attr (keyword attr)})))
    stats))

(defn annotation-lines!
  "The lines `cwb-s-decode` prints with `flags` for annotated s-attribute
  `attr` of `corpus` against the `ctx` registry (see `annotation-stats!`
  for the checks both names pass first); nil when the attribute has more
  than `region-limit` regions."
  [ctx corpus attr flags]
  (when (<= (:regions (annotation-stats! ctx corpus attr)) region-limit)
    (let [ctx (corpus/corpus-ctx ctx corpus)]
      (run-tool! ctx corpus (-> ["cwb-s-decode" "-r" (:registry ctx)]
                                (into flags)
                                (conj (str corpus) "-S" (name attr)))))))

(defn s-decode->freqs
  "Parse `lines` from `cwb-s-decode -n` (one annotation value per region,
  in corpus order) into frequency maps [{:values [<s>] :freq <n>} ...]
  sorted by value: how many regions carry each value, blank ones skipped;
  nil once there are more than `limit` distinct values."
  ([lines]
   (s-decode->freqs lines Long/MAX_VALUE))
  ([lines limit]
   (some->> (reduce (fn [m value]
                      (let [m (update m value (fnil inc 0))]
                        (if (> (count m) limit) (reduced nil) m)))
                    {}
                    (remove str/blank? lines))
            (sort-by key)
            (mapv (fn [[value n]] {:values [value] :freq n})))))

(defn annotation-values!
  "The values of annotated s-attribute `attr` of `corpus` (an uppercase
  CQP corpus name) with the number of regions carrying each, via
  `cwb-s-decode` against the `ctx` registry, cached until the corpus is
  re-encoded: [{:values [<s>] :freq <n>} ...] sorted by value (see
  `s-decode->freqs`), or nil when the attribute has too many values to
  list (see `value-limit` and `region-limit`)."
  [ctx corpus attr]
  (command/valid-corpus-name corpus)
  (corpus/facts!
   ctx corpus [::annotation-values (keyword attr)]
   (fn []
     (some-> (annotation-lines! ctx corpus attr ["-n"])
             (s-decode->freqs value-limit)))))

(defn s-decode->sizes
  "Parse `lines` from `cwb-s-decode` (start TAB end TAB annotation value,
  one line per region) into the number of tokens carrying each value,
  blank ones skipped: {<value> <tokens>}."
  [lines]
  (reduce (fn [m line]
            (let [[start end value] (str/split line #"\t" 3)]
              (if (str/blank? value)
                m
                (update m value (fnil + 0)
                        (inc (- (parse-long end) (parse-long start)))))))
          {}
          lines))

(defn annotation-sizes!
  "The number of tokens carrying each value of annotated s-attribute
  `attr` of `corpus` (an uppercase CQP corpus name), via `cwb-s-decode`
  against the `ctx` registry, cached until the corpus is re-encoded:
  {<value> <tokens>} (see `s-decode->sizes`), or nil when the attribute
  has too many regions to decode (see `region-limit`). No `value-limit`
  applies, this being a map a breakdown reads rather than a list of
  checkboxes."
  [ctx corpus attr]
  (command/valid-corpus-name corpus)
  (corpus/facts!
   ctx corpus [::annotation-sizes (keyword attr)]
   (fn []
     (some-> (annotation-lines! ctx corpus attr [])
             (s-decode->sizes)))))
