(ns dk.cst.corpus-probe.cwb.tools
  "Read-only wrappers for the cwb-* command-line tools, complementing the
  CQP driver with corpus facts CQP itself does not report, and the
  parsers of what the tools print.

  `cwb-describe-corpus` gives the corpus info pages their statistics,
  `cwb-lexdecode` gives whole-corpus frequency lists and `cwb-s-decode`
  gives the metadata filters their value lists and the frequency
  breakdowns the size of the text behind each value. Each parser is
  written against a byte-exact golden file (test/resources/golden/,
  regenerated by dev/capture-golden.sh)."
  (:require [clojure.string :as str]
            [dk.cst.corpus-probe.cwb :as cwb]
            [dk.cst.corpus-probe.cwb.command :as command]
            [dk.cst.corpus-probe.cwb.corpus :as corpus]))

(def tool-names
  "The CWB programs run here besides cqp. Each is invoked by bare name, so
  the PATH that reaches cqp has to reach these too."
  ["cwb-describe-corpus" "cwb-lexdecode" "cwb-s-decode"])

(defn run-tool!
  "Run the cwb tool command vector `cmd` for `corpus` via `ctx`, as
  dk.cst.corpus-probe.cwb.corpus/corpus-ctx configures it (the name
  validated, the :charset the corpus's own), and return its stdout lines.

  The output is decoded in that charset. Throws on `ctx`'s :timeout-ms
  (default 30000, destroying the process tree like the CQP driver) and on
  a non-zero exit, with the tool's error text; the registry diagnostics
  of dk.cst.corpus-probe.cwb/diagnostic? do not count as errors."
  [{:keys [timeout-ms charset] :or {timeout-ms 30000 charset "UTF-8"} :as ctx}
   corpus cmd]
  (let [res (cwb/run! cmd timeout-ms {:charset charset})]
    (when (cwb/timeout? res)
      (throw (ex-info "cwb tool timed out"
                      {:corpus corpus :cmd cmd :timeout-ms timeout-ms})))
    (when-not (zero? (:exit res))
      (throw (ex-info "cwb tool failed"
                      {:corpus corpus :cmd cmd :exit (:exit res)
                       :message (:error (cwb/stderr->outcome (:err res)))})))
    (str/split (:out res) #"\n")))

(defn describe->stats
  "Parse `lines` from `cwb-describe-corpus -s` (one corpus) into corpus
  facts with per-attribute statistics.

  Returns {:name <s> :description <s> :charset <s> :size <n>
  :p-attrs [{:name <kw> :tokens <n> :types <n>} ...]
  :s-attrs [{:name <kw> :regions <n> :values? <bool>} ...]
  :a-attrs [{:name <kw> :blocks <n>} ...]} with attributes in registry
  order. An attribute whose data files the tool cannot read (it prints
  NO DATA for it) keeps its name with nil counts; a corpus with no
  readable data has no :size. The registry/home/info paths in the output
  are dropped: they are server filesystem details, not corpus facts."
  [lines]
  (reduce (fn [m line]
            (condp re-matches line
              #"Corpus:\s+(\S+)" :>> (fn [[_ v]] (assoc m :name v))
              #"description:\s+(\S.*?)\s*" :>> (fn [[_ v]]
                                                 (assoc m :description v))
              #"encoding:\s+(\S+)\s*" :>> (fn [[_ v]] (assoc m :charset v))
              #"size \(tokens\):\s+(\d+)\s*" :>>
              (fn [[_ v]] (assoc m :size (parse-long v)))

              #"p-ATT (\S+)\s+(\d+) tokens,\s+(\d+) types\s*" :>>
              (fn [[_ n tokens types]]
                (update m :p-attrs conj {:name   (keyword n)
                                         :tokens (parse-long tokens)
                                         :types  (parse-long types)}))
              #"s-ATT (\S+)\s+(\d+) regions( \(with annotations\))?\s*" :>>
              (fn [[_ n regions values]]
                (update m :s-attrs conj {:name    (keyword n)
                                         :regions (parse-long regions)
                                         :values? (some? values)}))
              #"a-ATT (\S+)\s+(\d+) .*" :>>
              (fn [[_ n blocks]]
                (update m :a-attrs conj {:name   (keyword n)
                                         :blocks (parse-long blocks)}))
              #"([psa])-ATT (\S+)\s+NO DATA\s*" :>>
              (fn [[_ type n]]
                (update m ({"p" :p-attrs "s" :s-attrs "a" :a-attrs} type)
                        conj {:name (keyword n)}))
              m))
          {:p-attrs [] :s-attrs [] :a-attrs []}
          lines))

(defn describe-corpus!
  "Describe `corpus` (an uppercase CQP corpus name) with per-attribute
  statistics via `cwb-describe-corpus -s` against the `ctx` registry,
  cached until the corpus is re-encoded.

  Returns the map of `describe->stats`. The corpus name is validated
  first, like every name spliced into a command. Throws when the tool
  fails or times out, and when its output reports no size: the tool
  exits 0 for a registry entry whose data files are gone, printing ERROR
  in place of the size."
  [ctx corpus]
  (command/valid-corpus-name corpus)
  (corpus/facts!
   ctx corpus ::describe
   (fn []
     (let [ctx   (corpus/corpus-ctx ctx corpus)
           stats (describe->stats
                  (run-tool! ctx corpus ["cwb-describe-corpus"
                                         "-r" (:registry ctx)
                                         "-s" (str corpus)]))]
       (when (nil? (:size stats))
         (throw (ex-info "cwb-describe-corpus reported missing corpus data"
                         {:corpus corpus :phantom? true})))
       stats))))

(defn lexdecode->freqs
  "Parse `lines` from `cwb-lexdecode -fb` (frequency TAB value, one line
  per lexicon entry, in lexicon order) into frequency maps.

  Returns [{:values [<s>] :freq <n>} ...] sorted by descending frequency,
  the shape of dk.cst.corpus-probe.cwb.parse/group->freqs, so a
  whole-corpus lexicon and a grouped query result table alike."
  [lines]
  (->> (remove str/blank? lines)
       (map (fn [line]
              (let [[freq value] (str/split line #"\t" 2)]
                {:values [value] :freq (parse-long freq)})))
       (sort-by :freq >)
       (vec)))

(defn lexicon!
  "The frequency lexicon of positional attribute `attr` of `corpus` (an
  uppercase CQP corpus name) via `cwb-lexdecode -f` against the `ctx`
  registry.

  Returns [{:values [<s>] :freq <n>} ...] sorted by frequency (see
  `lexdecode->freqs`), the shape a grouped query result has, so the
  whole corpus can stand in for a query. Both names are spliced into the
  command: the corpus name is validated, and `attr` must be one of the
  corpus's positional attributes. Not cached: a large corpus's lexicon
  runs to millions of entries, too much heap to keep per attribute for
  the JVM's lifetime."
  ;; TODO: stream large lexicons and exports row by row instead of
  ;; building them in memory (milestone 5, with the NQR caching).
  [ctx corpus attr]
  (let [ctx (corpus/corpus-ctx ctx corpus)]
    (when-not (corpus/positional?
               (corpus/attribute (corpus/attributes! ctx corpus) attr))
      (throw (ex-info "Not a positional attribute of this corpus"
                      {:corpus corpus :attr attr})))
    (lexdecode->freqs
     (run-tool! ctx corpus ["cwb-lexdecode" "-r" (:registry ctx)
                            "-fb" "-P" (name attr) (str corpus)]))))

(def value-limit
  "The most distinct values an annotated s-attribute may have and still be
  offered as a metadata filter: a longer list of checkboxes is no longer a
  usable control, and a text ID or title has one value per region anyway."
  500)

(def region-limit
  "The most regions an s-attribute may have before its values are not
  even decoded: an attribute with millions of regions (sentence IDs, say)
  all but always exceeds `value-limit`, and decoding it costs seconds."
  1000000)

(defn attribute-values!
  "The values of positional attribute `attr` of `corpus` (an uppercase
  CQP corpus name) via `ctx`, in lexicon order, cached until the corpus
  is re-encoded; nil when the attribute has more than `value-limit`
  types (see `describe-corpus!`), which are not decoded, being no list a
  reader could pick from, or when the corpus lacks it. Both names are
  checked as `lexicon!` checks them."
  [ctx corpus attr]
  (command/valid-corpus-name corpus)
  (corpus/facts!
   ctx corpus [::attribute-values (keyword attr)]
   (fn []
     (let [types (:types (corpus/attribute
                          (:p-attrs (describe-corpus! ctx corpus)) attr))]
       (when (and types (<= types value-limit))
         (mapv (comp first :values) (lexicon! ctx corpus attr)))))))

(defn annotation-stats!
  "The describe statistics of annotated s-attribute `attr` of `corpus`
  (an uppercase CQP corpus name) via `ctx`: its name and its region
  count (see `describe-corpus!`).

  Both names are spliced into the command that decodes the attribute, so
  the corpus name is validated and anything but an annotated
  s-attribute of the corpus is rejected."
  [ctx corpus attr]
  (let [stats (corpus/attribute (:s-attrs (describe-corpus! ctx corpus))
                                attr)]
    (when-not (:values? stats)
      (throw (ex-info "Not an annotated structural attribute of this corpus"
                      {:corpus corpus :attr (keyword attr)})))
    stats))

(defn annotation-lines!
  "The lines `cwb-s-decode` prints with `flags` for annotated
  s-attribute `attr` of `corpus` against the `ctx` registry (see
  `annotation-stats!` for the checks both names pass first); nil when
  the attribute has more than `region-limit` regions, which are not even
  decoded."
  [ctx corpus attr flags]
  (when (<= (:regions (annotation-stats! ctx corpus attr)) region-limit)
    (let [ctx (corpus/corpus-ctx ctx corpus)]
      (run-tool! ctx corpus (-> ["cwb-s-decode" "-r" (:registry ctx)]
                                (into flags)
                                (conj (str corpus) "-S" (name attr)))))))

(defn s-decode->freqs
  "Parse `lines` from `cwb-s-decode -n` (one annotation value per region,
  in corpus order) into frequency maps: how many regions carry each
  value; nil once there are more than `limit` distinct values.

  Returns [{:values [<s>] :freq <n>} ...] sorted by value, the shape of
  dk.cst.corpus-probe.cwb.parse/group->freqs, so the value lists of
  several corpora merge like frequency tables. Blank lines (the trailing
  one, and regions with a blank value) are skipped. The count stops as
  soon as the limit is passed, so an attribute with a value per region
  costs little."
  ([lines]
   (s-decode->freqs lines Long/MAX_VALUE))
  ([lines limit]
   (some->> (reduce (fn [m value]
                      (let [m (update m value (fnil inc 0))]
                        (if (> (count m) limit) (reduced nil) m)))
                    {}
                    (remove str/blank? lines))
            (sort-by key)
            (mapv (fn [[value n]] {:values [value] :freq n})))))

(defn annotation-values!
  "The values of annotated s-attribute `attr` of `corpus` (an uppercase
  CQP corpus name) with the number of regions carrying each, via
  `cwb-s-decode` against the `ctx` registry, cached until the corpus is
  re-encoded.

  Returns [{:values [<s>] :freq <n>} ...] sorted by value (see
  `s-decode->freqs`), or nil when the attribute has too many values to
  list (see `value-limit` and `region-limit`). Both names are checked
  before anything is decoded (see `annotation-lines!`)."
  [ctx corpus attr]
  (command/valid-corpus-name corpus)
  (corpus/facts!
   ctx corpus [::annotation-values (keyword attr)]
   (fn []
     (some-> (annotation-lines! ctx corpus attr ["-n"])
             (s-decode->freqs value-limit)))))

(defn s-decode->sizes
  "Parse `lines` from `cwb-s-decode` (start TAB end TAB annotation value,
  one line per region, in corpus order) into the number of tokens
  carrying each value: {<value> <tokens>}.

  A region spans its end position less its start, plus one. Blank lines
  (the trailing one, and regions with a blank value) are skipped, as
  `s-decode->freqs` skips them."
  [lines]
  (reduce (fn [m line]
            (let [[start end value] (str/split line #"\t" 3)]
              (if (str/blank? value)
                m
                (update m value (fnil + 0)
                        (inc (- (parse-long end) (parse-long start)))))))
          {}
          lines))

(defn annotation-sizes!
  "The number of tokens carrying each value of annotated s-attribute
  `attr` of `corpus` (an uppercase CQP corpus name), via `cwb-s-decode`
  against the `ctx` registry, cached until the corpus is re-encoded.

  Returns {<value> <tokens>} (see `s-decode->sizes`), or nil when the
  attribute has too many regions to decode (see `region-limit`). What a
  rate per million is measured against when a breakdown groups by the
  attribute: the text carrying each value rather than the whole corpus,
  so that a year with more text does not look busier. No `value-limit`
  applies, this being a map a breakdown reads rather than a list of
  checkboxes. Both names are checked as `annotation-values!` checks
  them."
  [ctx corpus attr]
  (command/valid-corpus-name corpus)
  (corpus/facts!
   ctx corpus [::annotation-sizes (keyword attr)]
   (fn []
     (some-> (annotation-lines! ctx corpus attr [])
             (s-decode->sizes)))))
