(ns dk.cst.corpus-probe.parse
  "Parsers turning CQP/CWB terminal output into plain data.

  Every parser here is written against byte-exact golden files captured from
  a real CQP session (test/resources/golden/, regenerated by
  dev/capture-golden.sh). KWIC lines are expected in the hardened display
  profile of dk.cst.corpus-probe.query: all separators are TAB-framed marker
  letters, and TAB/LF are the only bytes CWB can never emit inside a
  positional-attribute value, so splitting on TAB yields fields that
  alternate strictly between values (even indices) and single-letter markers
  (odd indices)."
  (:require [clojure.string :as str]))

(defn- finish-token
  "Close the token accumulating in `acc` and file it under the current zone."
  [{:keys [attrs zone parts open close] :as acc}]
  (-> acc
      (cond-> (or (seq (remove empty? parts)) (seq open) (seq close))
        (update zone conj (cond-> (zipmap attrs parts)
                            (seq open)  (assoc :open open)
                            (seq close) (assoc :close close))))
      (assoc :parts [] :open [] :close [])))

(defn- add-tag
  "Record structure tag `v` (e.g. \"<s>\" or \"</s>\") on the token in `acc`."
  [acc v]
  (let [close? (str/starts-with? v "</")
        tag    (keyword (str/replace v #"[</>]" ""))]
    (update acc (if close? :close :open) conj tag)))

(defn kwic-line->hit
  "Parse one hardened-profile KWIC `line` into a hit map with the token
  attributes named by `attrs` (in the order they are shown).

  Returns {:cpos <n> :left [token ...] :match [...] :right [...]} where each
  token is a map of attribute keyword to value, plus :open/:close vectors of
  structure-tag keywords when tags are shown. Empty fields adjacent to the
  T/L/R/S frame markers are separator glue and are dropped; an empty
  attribute value survives because it neighbours an A marker. Throws when
  `line` lacks the corpus-position prefix of a KWIC line."
  [attrs line]
  (let [[_ cpos content] (re-matches #"(?s)\s*(\d+): (.*)" line)
        _      (when-not cpos
                 (throw (ex-info "Not a KWIC line" {:line line})))
        fields (str/split content #"\t" -1)
        pairs  (partition-all 2 fields)
        triples (map (fn [[v m] prev-m] [v m prev-m])
                     pairs
                     (cons nil (map second pairs)))]
    (-> (reduce
         (fn [{:keys [in-tag?] :as acc} [v m prev-m]]
           (let [acc (cond
                       in-tag?
                       (add-tag acc v)

                       (or (not-empty v) (= prev-m "A") (= m "A"))
                       (update acc :parts conj v)

                       :else acc)]
             (case m
               "A" acc
               "S" (update acc :in-tag? not)
               "T" (finish-token acc)
               "L" (-> acc finish-token (assoc :zone :match))
               "R" (-> acc finish-token (assoc :zone :right))
               nil (finish-token acc))))
         {:attrs attrs :zone :left :in-tag? false
          :parts [] :open [] :close []
          :left [] :match [] :right []}
         triples)
        (select-keys [:left :match :right])
        (assoc :cpos (parse-long cpos)))))

(defn kwic->hits
  "Parse hardened-profile KWIC `lines` (from `cat`) using `attrs`."
  [attrs lines]
  (mapv (partial kwic-line->hit attrs) lines))

(defn show-cd->attributes
  "Parse `lines` from `show cd;` into attribute descriptions.

  Returns [{:type :positional/:structural/:alignment :name <kw>
  :values? <bool> :shown? <bool>} ...] in registry order."
  [lines]
  (vec (for [line lines
             :let [[type name values shown] (str/split line #"\t" -1)]
             :when (not-empty type)]
         {:type    ({"p-Att" :positional
                     "s-Att" :structural
                     "a-Att" :alignment} type)
          :name    (keyword name)
          :values? (= values "-V")
          :shown?  (= shown "*")})))

(defn dump->anchors
  "Parse `lines` from `dump` into anchor maps, one per match.

  Returns [{:match <n> :matchend <n> :target <n or nil> :keyword <n or nil>}
  ...]; CQP prints -1 for unset anchors, translated here to nil."
  [lines]
  (mapv (fn [line]
          (let [[match matchend target keyword*]
                (map parse-long (str/split line #"\t"))]
            {:match    match
             :matchend matchend
             :target   (when-not (= -1 target) target)
             :keyword  (when-not (= -1 keyword*) keyword*)}))
        lines))

(defn group->freqs
  "Parse `lines` from `group` into frequency maps.

  Returns [{:values [<s>] :freq <n>} ...]. The frequency is split off from
  the right, so an annotation value containing TAB stays intact."
  [lines]
  (mapv (fn [line]
          (let [[_ value freq] (re-matches #"(?s)(.*)\t(\d+)" line)]
            {:values [value] :freq (parse-long freq)}))
        lines))

(defn lexicon->freqs
  "Parse `lines` from `cwb-lexdecode -fb` (frequency TAB value, one line per
  lexicon entry, in lexicon order) into frequency maps.

  Returns [{:values [<s>] :freq <n>} ...] sorted by descending frequency,
  the shape of `group->freqs`, so a whole-corpus lexicon and a grouped
  query result table alike."
  [lines]
  (->> (remove str/blank? lines)
       (map (fn [line]
              (let [[freq value] (str/split line #"\t" 2)]
                {:values [value] :freq (parse-long freq)})))
       (sort-by :freq >)
       (vec)))

(defn s-decode->freqs
  "Parse `lines` from `cwb-s-decode -n` (one annotation value per region,
  in corpus order) into frequency maps: how many regions carry each
  value; nil once there are more than `limit` distinct values.

  Returns [{:values [<s>] :freq <n>} ...] sorted by value, the shape of
  `group->freqs`, so the value lists of several corpora merge like
  frequency tables. Blank lines (the trailing one, and regions with a
  blank value) are skipped. The count stops as soon as the limit is
  passed, so an attribute with a value per region costs little."
  ([lines]
   (s-decode->freqs lines Long/MAX_VALUE))
  ([lines limit]
   (some->> (reduce (fn [m value]
                      (let [m (update m value (fnil inc 0))]
                        (if (> (count m) limit) (reduced nil) m)))
                    {}
                    (remove str/blank? lines))
            (sort-by key)
            (mapv (fn [[value n]] {:values [value] :freq n})))))

(defn describe->map
  "Parse `lines` from `cwb-describe-corpus -s` (one corpus) into corpus
  facts with per-attribute statistics.

  Returns {:name <s> :description <s> :charset <s> :size <n>
  :p-attrs [{:name <kw> :tokens <n> :types <n>} ...]
  :s-attrs [{:name <kw> :regions <n> :values? <bool>} ...]
  :a-attrs [{:name <kw> :blocks <n>} ...]} with attributes in registry
  order. An attribute whose data files the tool cannot read (it prints
  NO DATA for it) keeps its name with nil counts; a corpus with no
  readable data has no :size. The registry/home/info paths in the output
  are dropped: they are server filesystem details, not corpus facts."
  [lines]
  (reduce (fn [m line]
            (condp re-matches line
              #"Corpus:\s+(\S+)" :>> (fn [[_ v]] (assoc m :name v))
              #"description:\s+(\S.*?)\s*" :>> (fn [[_ v]]
                                                 (assoc m :description v))
              #"encoding:\s+(\S+)\s*" :>> (fn [[_ v]] (assoc m :charset v))
              #"size \(tokens\):\s+(\d+)\s*" :>>
              (fn [[_ v]] (assoc m :size (parse-long v)))

              #"p-ATT (\S+)\s+(\d+) tokens,\s+(\d+) types\s*" :>>
              (fn [[_ n tokens types]]
                (update m :p-attrs conj {:name   (keyword n)
                                         :tokens (parse-long tokens)
                                         :types  (parse-long types)}))
              #"s-ATT (\S+)\s+(\d+) regions( \(with annotations\))?\s*" :>>
              (fn [[_ n regions values]]
                (update m :s-attrs conj {:name    (keyword n)
                                         :regions (parse-long regions)
                                         :values? (some? values)}))
              #"a-ATT (\S+)\s+(\d+) .*" :>>
              (fn [[_ n blocks]]
                (update m :a-attrs conj {:name   (keyword n)
                                         :blocks (parse-long blocks)}))
              #"([psa])-ATT (\S+)\s+NO DATA\s*" :>>
              (fn [[_ type n]]
                (update m ({"p" :p-attrs "s" :s-attrs "a" :a-attrs} type)
                        conj {:name (keyword n)}))
              m))
          {:p-attrs [] :s-attrs [] :a-attrs []}
          lines))

(defn info->map
  "Parse `lines` from `info;` into corpus facts.

  Returns {:name <s> :size <n> :charset <s> :properties {<kw> <s>} :info <s>}
  where :info is the free-text content of the corpus's .info file. Only the
  lines before the first blank line are treated as the header block; the
  .info content after it is kept verbatim, so colon-shaped lines in it
  cannot clobber the corpus facts."
  [lines]
  (let [[header body] (split-with (complement str/blank?) lines)
        info          (str/join "\n" (drop-while str/blank? body))]
    (cond-> (reduce (fn [m line]
                      (if-let [[_ k v] (re-matches #"([A-Za-z]+):\s*(.*)" line)]
                        (case k
                          "Name"    (assoc m :name v)
                          "Size"    (assoc m :size (parse-long v))
                          "Charset" (assoc m :charset v)
                          m)
                        (if-let [[_ k v] (re-matches #"\t(\S+) = '(.*)'" line)]
                          (assoc-in m [:properties (keyword k)] v)
                          m)))
                    {:properties {}}
                    header)
      (not-empty info) (assoc :info info))))
